config/routes.rb
RailsHero::Application.routes.draw do

  resources :videos


  devise_for :users

  root :to => 'dynamic_pages#home'

  devise_scope :user do
    get "/signin" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    get "/signout" => "devise/sessions#destroy"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    if user==nil
      user ||= User.new
      user.role="guest"
    end
    if user.role == "admin"
      can :manage, :all
    elsif user.role == "mentor"
      can :create, [Video]
      can :update, [Video]
      can [:update, :destroy], [User] do |u|
        u.try(:id) == user.id
      end   
    elsif user.role == "student"
      can [:update, :destroy], [User] do |u|
        u.try(:id) == user.id
      end
      can :read, :all
    elsif user.role =="user"
      can [:update, :destroy], [User] do |u|
        u.try(:id) == user.id
      end
      
    else
      can :read, :all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_name
  validates :user_name, :email, :encrypted_password, :presence => true
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :video_description, :video_title, :youtube_link, :course_number, :course_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  skip_authorization_check 
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /users
  # GET /users.json
  def index
    #@users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    #@user = User.find(params[:id])
    # @user.picture.build
  end

  # POST /users
  # POST /users.json
  def create
    #@user = User.new(params[:user])
    @mixpanel.append_api("Sign up", {:name => @user.name})
    @mixpanel.append_api("identify", @user.id.to_s)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    #@user = User.find(params[:id])
    #@user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  load_and_authorize_resource
  skip_authorization_check :only => [:show, :index]
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Rails Hero"
    if page_title.empty?
      base_title="Rails Hero | Learn to Code with a Hero"
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/dynamic_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="row">
  <div id="landingHeader" class="span12">
    <div class="row">
        <div class="hidden-phone hidden-tablet"><div id="moon" class="span3"><%= image_tag("moon.png") %></div></div>
    </div>
    <div class="row">
      <div id="callout" class="span6 offset5">
        <div class="row">
            <div class="span5">
              <% if current_user == nil %>
                <%= render :partial => "dynamic_pages/home_partials/guest_hero" %>
              <% else %>
                <%= render :partial => "dynamic_pages/home_partials/user_hero" %>
              <% end %>
            </div> 
        </div>
      </div>
    </div>
    <div class="row">
      <div class="hidden-phone">
        <div id="skyline" class="span12"> <%= image_tag("heroskyline.png") %></div>
      </div>
    </div>
  </div>
</div>

app/views/dynamic_pages/home_partials/_guest_hero.html.erb
<h1>Learn to code, with the help of a tutor.</h1>
<p>
  Learn how to code while building your sideproject, or build one of our starter apps. 
</p>
<p>
   We remember what it was like to learn how to code. Jump start your education by getting help from the pros.
</p>
  <button class="btn btn-large btn-warning" type="button">Enroll Now!</button>

app/views/dynamic_pages/home_partials/_user_hero.html.erb
<h1>Welcome Back,</h1>
<br>
<h1> <%=current_user.email%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navibar">
      <div class="container">
        <div class="hidden-desktop hidden-tablet">
          <div id="mobilelogo"><%= image_tag("mobilelogo.png") %></div>
        </div>
        <div class="hidden-phone">
          <div id="logo"><%= link_to image_tag("logo.png"), root_path, id: "logo" %></div>
        </div>
        <nav>
          <ul class="nav pull-left">
            <% if current_user %>
              <li><%= link_to "videos", videos_path %></li>
              <li><%= link_to "tutoring sessions", '#' %></li>
              <li><%= link_to "sign out", signout_path %></li>
            <% else %>
              <li><%= link_to "free videos",    videos_path %></li>
              <li><%= link_to "pricing",    '#' %></li>
              <li><%= link_to "sign in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_title %><br />
    <%= f.text_field :video_title %>
  </div>
  <div class="field">
    <%= f.label :video_description %><br />
    <%= f.text_area :video_description %>
  </div>
  <div class="field">
    <%= f.label :youtube_link %><br />
    <%= f.text_field :youtube_link %>
  </div>
    <div class="field">
    <%= f.label :course_number %><br />
    <%= f.text_field :course_number %>
  </div>
    <div class="field">
    <%= f.label :course_name %><br />
    <%= f.text_field :course_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Learn for Free</h1>
<h2>These beginner friendly videos are for you. <br>When you get to the point where you need some one on one help, we are here to help.</h2>
<div id='video-button'>
  <button class="btn btn-large btn-warning" type="button">I Need a Hero!</button>
  <p>enroll for one on one tutoring today</p>
</div>
<br>
<br>
<h3>Introduction to Ruby and Programming (RB101)</h3>
<table class="table">
  <tr>
    <th>Video title</th>
    <th>Video description</th>
    <th>Course Name</th>
    <th>Course Number</th>
    <% if can? :update, Video %><th>Edit Actions</th><% end %>
    <% if can? :destroy, Video %><th>Destroy</th><% end %>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= link_to video.video_title, video %></td>
    <td><%= link_to video.video_description, video %></td>
    <td><%= link_to video.course_name, video %></td>
    <td><%= link_to video.course_number, video %></td>
    <% if can? :update, Video %><td><%= link_to 'Edit', edit_video_path(video) %></td><% end %>
    <% if can? :destroy, Video %><td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
  </tr>
<% end %>
</table>
<% if can? :create, Video %>
  <%= link_to 'New Video', new_video_path %>
<% end %>
<br />
<br />
<br />
<br />

<h3>In development: "Building our first Ruby Application, for beginners"</h3>

<br />

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Video title:</b>
  <%= @video.video_title %>
</p>

<p>
  <b>Video description:</b>
  <%= @video.video_description %>
</p>

<p>
  <b>Youtube link:</b>
  <%= @video.youtube_link %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>